### PR TITLE
Streamline K8s Challenge by Abstracting Steps and Reducing Details

### PR DESCRIPTION
**Pull request by nimeshmora**
Hello Forrest,

We've made some adjustments by making certain steps more abstract and less detailed, allowing end users to apply their own understanding to the solutions. However, we have decided not to alter or omit details from step 2, where we focus on containerizing the web app and database. Given these components are application-specific, we believe it's beneficial to provide some detailed guidance, especially concerning aspects unique to PHP web applications and the `db-load-script.sql`. These specifics might not be easily deduced by users, so including them is advantageous.

We have also removed the previous version's "Step 06 - Add a feature toggle to the web application to enable a 'dark mode' for the website." This step required making changes to a PHP web application, which looks like falling outside the intended scope of this challenge. We aim to avoid placing users in the role of developers. However, the aspect of configuration maps is addressed in Step 11 of the new version.

The other steps have been made somewhat more abstract compared to the previous version.

### CODE REVIEW

**Comment by nimeshmora** [comment]
@forrestbrazeal

**Comment by forrestbrazeal** [comment]
Thanks for the dialogue here, @loujaybee and @nimeshmora. I've taken a look at both of your pull requests and appreciate the intent.

Given that we're just a few days from kicking off the March sprint and a large number of folks have already made the choice to participate based on the existing challenge version, I think the fairest call is to hold off on both of these PRs and keep the challenge as-is for this month.

However, for upcoming monthly challenges I definitely want to continue steering us toward the right mix of helpful specifications and self-guided learning. @loujaybee would you be interested in reworking your take on the k8s challenge as a standalone project for April?

**Comment by loujaybee** [comment]
@forrestbrazeal sounds logical/reasonable. Let's get through this first cohort and then reflect and adjust if needed ! 

The current instructions are more than sufficient. Any questions can always be fielded in Discord. 

🙏 🚀 - Thanks both, let's chat again in April !

**Comment by nimeshmora** [comment]
@forrestbrazeal we have developed a new resource that would benefit users to review before taking the challenge. Could we incorporate that link into the current version and submit a PR, please?

The following would be a good resource + free lab links: 

- Checkout the KodeKloud's [Kubernetes Crash Course](https://kodekloud.com/pages/kubernetes-crash-course?utm_source=cloudresumechallenge.dev&utm_medium=referral&utm_campaign=cloud_resume_challenge_kube_crash_course).

or could you please add the above bullet to the prerequisites section @forrestbrazeal

**Comment by forrestbrazeal** [comment]
Sure thing, @nimeshmora - I've added the link both to this repo and to the CRC site.

**Comment by forrestbrazeal** [comment]
> @forrestbrazeal sounds logical/reasonable. Let's you get through this first cohort and then reflect and adjust if needed !
> 
> The current instructions are more than sufficient. Any questions can always be fielded in Discord.
> 
> 🙏 🚀 - Thanks both, let's chat again in April !

Appreciate the dialogue! Closing this PR for now, let's revisit soon.

**Pull request closed without merging**
